export const ADD_VIEW_MESSAGE = 'VIEWTRON_ADD_VIEW_MESSAGE';
export const SET_VIEW_RECT_OVERRIDE_MESSAGE = 'VIEWTRON_SET_VIEW_RECT_OVERRIDE_MESSAGE';
export const RESET_VIEW_RECTS_MESSAGE = 'VIEWTRON_RESET_VIEW_RECTS_MESSAGE';
export const REMOVE_VIEW_MESSAGE = 'VIEWTRON_REMOVE_VIEW_MESSAGE';
export const VIEW_AREA_INIT_MESSAGE = 'VIEWTRON_VIEW_AREA_INIT_MESSAGE';
export const VIEW_AREA_RESIZE_MESSAGE = 'VIEWTRON_VIEW_AREA_RESIZE_MESSAGE';
export const VIEWS_UPDATED_MESSAGE = 'VIEWTRON_VIEWS_UPDATED_MESSAGE';
