import {ViewtronConfig} from './types';

export const VIEWTRON_INIT_MESSAGE = 'VIEWTRON_VIEWTRON_INIT_MESSAGE';
export const VIEWTRON_RESIZE_MESSAGE = 'VIEWTRON_VIEWTRON_RESIZE_MESSAGE';
export const VIEWTRON_UPDATE_MESSAGE = 'VIEWTRON_VIEWTRON_UPDATE_MESSAGE';
export const VIEWTRON_SET_LAYOUT_MESSAGE = 'VIEWTRON_VIEWTRON_SET_LAYOUT_MESSAGE';

export const ADD_ROW_MESSAGE = 'VIEWTRON_ADD_ROW_MESSAGE';
export const REMOVE_ROW_MESSAGE = 'VIEWTRON_REMOVE_ROW_MESSAGE';
export const REORDER_ROW_MESSAGE = 'VIEWTRON_REORDER_ROW_MESSAGE';
export const SET_ROW_HEIGHTS_OVERRIDE_MESSAGE = 'VIEWTRON_SET_ROW_HEIGHTS_OVERRIDE_MESSAGE';
export const SET_ROW_VISIBILITY_MESSAGE = 'VIEWTRON_SET_ROW_VISIBILITY_MESSAGE';
export const RESET_ROW_HEIGHTS_MESSAGE = 'VIEWTRON_RESET_ROW_HEIGHTS_MESSAGE';

export const ADD_COLUMN_MESSAGE = 'VIEWTRON_ADD_COLUMN_MESSAGE';
export const REMOVE_COLUMN_MESSAGE = 'VIEWTRON_REMOVE_COLUMN_MESSAGE';
export const REORDER_COLUMN_MESSAGE = 'VIEWTRON_VIEW_REORDER_COLUMN_MESSAGE';
export const SET_COLUMN_WIDTHS_OVERRIDE_MESSAGE = 'VIEWTRON_SET_COLUMN_WIDTHS_OVERRIDE_MESSAGE';
export const SET_COLUMN_VISIBILITY_MESSAGE = 'VIEWTRON_SET_COLUMN_VISIBILITY_MESSAGE';
export const RESET_COLUMN_WIDTHS_MESSAGE = 'VIEWTRON_RESET_COLUMN_WIDTHS_MESSAGE';

export const ADD_VIEW_MESSAGE = 'VIEWTRON_ADD_VIEW_MESSAGE';
export const REMOVE_VIEW_MESSAGE = 'VIEWTRON_REMOVE_VIEW_MESSAGE';
export const REORDER_VIEW_MESSAGE = 'VIEWTRON_REORDER_VIEW_MESSAGE';
export const SET_VIEW_HEIGHT_OVERRIDE_MESSAGE = 'VIEWTRON_SET_VIEW_HEIGHT_OVERRIDE_MESSAGE';
export const SET_VIEW_VISIBILITY_MESSAGE = 'VIEWTRON_SET_VIEW_VISIBILITY_MESSAGE';
export const RESET_VIEW_HEIGHTS_MESSAGE = 'VIEWTRON_RESET_VIEW_HEIGHTS_MESSAGE';

export const DEFAULT_CONFIG: ViewtronConfig = {
    spacing: 10,
    minWidth: 50,
    minHeight: 50,
    responsive: true,
    destroyOnClose: true,
    browserViewDefaultOptions: {}
};
