import {ViewtronConfig} from './types';

export const ADD_VIEW_MESSAGE = 'VIEWTRON_ADD_VIEW_MESSAGE';
export const SET_VIEW_HEIGHT_OVERRIDE_MESSAGE = 'VIEWTRON_SET_VIEW_HEIGHT_OVERRIDE_MESSAGE';
export const RESET_VIEW_HEIGHTS_MESSAGE = 'VIEWTRON_RESET_VIEW_HEIGHTS_MESSAGE';
export const REMOVE_VIEW_MESSAGE = 'VIEWTRON_REMOVE_VIEW_MESSAGE';

export const VIEW_AREA_INIT_MESSAGE = 'VIEWTRON_VIEW_AREA_INIT_MESSAGE';
export const VIEW_AREA_RESIZE_MESSAGE = 'VIEWTRON_VIEW_AREA_RESIZE_MESSAGE';
export const VIEW_ADD_COLUMN_MESSAGE = 'VIEWTRON_VIEW_ADD_COLUMN_MESSAGE';
export const VIEW_REMOVE_COLUMN_MESSAGE = 'VIEWTRON_VIEW_REMOVE_COLUMN_MESSAGE';
export const SET_COLUMN_WIDTH_OVERRIDE_MESSAGE = 'VIEWTRON_SET_COLUMN_WIDTH_OVERRIDE_MESSAGE';
export const VIEW_ADD_ROW_MESSAGE = 'VIEWTRON_VIEW_ADD_ROW_MESSAGE';
export const VIEW_REMOVE_ROW_MESSAGE = 'VIEWTRON_VIEW_REMOVE_ROW_MESSAGE';
export const SET_ROW_OVERRIDE_OVERRIDE_MESSAGE = 'VIEWTRON_SET_ROW_OVERRIDE_OVERRIDE_MESSAGE';

export const VIEWS_UPDATED_MESSAGE = 'VIEWTRON_VIEWS_UPDATED_MESSAGE';

export const DEFAULT_CONFIG: ViewtronConfig = {
    spacing: 5,
    minWidth: 50,
    minHeight: 50,
    responsive: true
};
